"""cascade add to resume

Revision ID: 26070ff0495f
Revises: 3d152f686fc4
Create Date: 2025-12-21 21:21:46.862938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26070ff0495f'
down_revision: Union[str, Sequence[str], None] = '3d152f686fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.drop_constraint(op.f('resumes_user_id_fkey'), 'resumes', type_='foreignkey')
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.create_foreign_key(op.f('resumes_user_id_fkey'), 'resumes', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    # ### end Alembic commands ###
