"""fk add

Revision ID: 3d152f686fc4
Revises: e34dd963435f
Create Date: 2025-12-21 21:16:46.522453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d152f686fc4'
down_revision: Union[str, Sequence[str], None] = 'e34dd963435f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'resume_improvements', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'resume_improvements', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resume_improvements', type_='foreignkey')
    op.drop_constraint(None, 'resume_improvements', type_='foreignkey')
    # ### end Alembic commands ###
