"""add resume_improvements

Revision ID: e34dd963435f
Revises: c5f1327f2037
Create Date: 2025-12-15 08:05:33.240186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e34dd963435f'
down_revision: Union[str, Sequence[str], None] = 'c5f1327f2037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_improvements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=False),
    sa.Column('improved_content', sa.Text(), nullable=False),
    sa.Column('is_preview', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_improvements_id'), 'resume_improvements', ['id'], unique=False)
    op.create_index(op.f('ix_resume_improvements_is_preview'), 'resume_improvements', ['is_preview'], unique=False)
    op.create_index(op.f('ix_resume_improvements_resume_id'), 'resume_improvements', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_improvements_user_id'), 'resume_improvements', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_improvements_user_id'), table_name='resume_improvements')
    op.drop_index(op.f('ix_resume_improvements_resume_id'), table_name='resume_improvements')
    op.drop_index(op.f('ix_resume_improvements_is_preview'), table_name='resume_improvements')
    op.drop_index(op.f('ix_resume_improvements_id'), table_name='resume_improvements')
    op.drop_table('resume_improvements')
    # ### end Alembic commands ###
